# Generated by Django 4.1 on 2022-08-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('layout', models.CharField(choices=[('60%', '60%'), ('65%', '65%'), ('75%', '75%'), ('80%', '80%'), ('95%', '95%'), ('100%', '100%')], default=0, max_length=10)),
                ('pcb', models.CharField(choices=[('H', 'Hotswap'), ('S', 'Solderable')], default=0, max_length=10)),
                ('plate', models.CharField(choices=[('AL', 'Aluminum'), ('BR', 'Brass'), ('CF', 'Carbon Fiber'), ('FR', 'FR-4'), ('PC', 'Poly-Carbonate'), ('PM', 'POM'), ('ST', 'Steel')], default=0, max_length=10)),
            ],
        ),
    ]
