# Generated by Django 4.1 on 2022-08-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='layout',
            field=models.CharField(choices=[('60%', '60%'), ('65%', '65%'), ('75%', '75%'), ('80%', '80%'), ('95%', '95%'), ('100%', '100%')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='pcb',
            field=models.CharField(choices=[('Hotswap', 'Hotswap'), ('Solderable', 'Solderable')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='plate',
            field=models.CharField(choices=[('Aluminum', 'Aluminum'), ('Brass', 'Brass'), ('Carbon Fiber', 'Carbon Fiber'), ('FR-4', 'FR-4'), ('Poly-Carbonate', 'Poly-Carbonate'), ('PM', 'POM'), ('Steel', 'Steel')], default=0, max_length=50),
        ),
    ]
