# Generated by Django 4.1 on 2022-08-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_switch_alter_keyboard_layout_alter_keyboard_pcb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='plate',
            field=models.CharField(choices=[('Aluminum', 'Aluminum'), ('Brass', 'Brass'), ('Carbon Fiber', 'Carbon Fiber'), ('FR-4', 'FR-4'), ('Poly-Carbonate', 'Poly-Carbonate'), ('POM', 'POM'), ('Steel', 'Steel')], default=0, max_length=50),
        ),
    ]
