# Generated by Django 4.1 on 2022-08-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_keyboard_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='bottom_housing',
            field=models.CharField(choices=[('POM', 'POM'), ('Polycarbonate', 'Polycarbonate'), ('Nylon', 'Nylon'), ('PE', 'PE'), ('UHMWPE', 'UHMWPE'), ('Mixed', 'Mixed')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='switch',
            name='pin',
            field=models.CharField(choices=[('5-pin', '5-pin'), ('3-pin', '3-pin')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='switch',
            name='spring',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Color Coated', 'Color Coated'), ('Gold-plated', 'Gold-plated'), ('Progressive', 'Progressive')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='switch',
            name='stem',
            field=models.CharField(choices=[('POM', 'POM'), ('Polycarbonate', 'Polycarbonate'), ('Nylon', 'Nylon'), ('PE', 'PE'), ('UHMWPE', 'UHMWPE'), ('Mixed', 'Mixed')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='switch',
            name='top_housing',
            field=models.CharField(choices=[('POM', 'POM'), ('Polycarbonate', 'Polycarbonate'), ('Nylon', 'Nylon'), ('PE', 'PE'), ('UHMWPE', 'UHMWPE'), ('Mixed', 'Mixed')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='switch',
            name='type',
            field=models.CharField(choices=[('Linear', 'Linear'), ('Tactile', 'Tactile'), ('Clicky', 'Clicky')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='plate',
            field=models.CharField(choices=[('Aluminum', 'Aluminum'), ('Brass', 'Brass'), ('Carbon Fiber', 'Carbon Fiber'), ('FR-4', 'FR-4'), ('Polycarbonate', 'Polycarbonate'), ('POM', 'POM'), ('Steel', 'Steel')], default=0, max_length=50),
        ),
    ]
