# Generated by Django 4.1 on 2022-08-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_switch_bottom_housing_switch_pin_switch_spring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='switches',
            field=models.ManyToManyField(to='main_app.switch'),
        ),
    ]
