# Generated by Django 4.1 on 2022-08-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_keyboard_switches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboard',
            name='switches',
        ),
    ]
