# Generated by Django 4.1 on 2022-08-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_keyboard_switches_keyboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='actuation_force',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='switch',
            name='bottom_out',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
