# Generated by Django 4.1 on 2022-08-12 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_switch_actuation_force_switch_bottom_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboard',
            name='switches',
        ),
        migrations.AddField(
            model_name='keyboard',
            name='switches',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.switch'),
            preserve_default=False,
        ),
    ]
