# Generated by Django 4.1 on 2022-08-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_keyboard_switches_keyboard_switches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboard',
            name='switches',
        ),
    ]
